name: Build Sal Bel Full Set
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Full Solution
        run: |
          cd "injector src"
          msbuild injector.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SalBel_Full_Bundle
          # Dùng đường dẫn này để GitHub tự tìm mọi file .exe và .dll vừa tạo ra
          path: |
            **/*.exe
            **/*.dll
          # Dòng này giúp bỏ qua các file rác của hệ thống
          if-no-files-found: error
