name: Build Sal Bel 90dB
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Project
        # Nhớ kiểm tra lại tên file .sln của bạn có đúng là injector.sln không nhé
        run: msbuild injector.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: SalBel_90dB_Final
          path: |
            x64/Release/*.dll
            x64/Release/*.exe
